name: Build

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.18.0'

    - name: Tests
      run: go test
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}